Vagrant.configure("2") do |config|
  

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"

     ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
     ubuntu.vm.synced_folder "d:/machine/projects", "/vagrant_data"
    ubuntu.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
   SHELL
          
  
  end
  

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "forwarded_port", guest: 84, host: 8480
  end
 end